# Generated by Django 4.2.11 on 2024-04-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='employees', verbose_name='Снимка')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='Име и фамилия')),
                ('position', models.CharField(blank=True, default='', max_length=50, verbose_name='Длъжност')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание/резюме')),
            ],
            options={
                'verbose_name': 'Служител',
                'verbose_name_plural': 'Служители',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to='employees', verbose_name='Снимка горе ляво')),
                ('photo2', models.ImageField(blank=True, upload_to='employees', verbose_name='Снимка горе дясно')),
                ('photo3', models.ImageField(blank=True, upload_to='employees', verbose_name='Снимка долу ляво')),
                ('photo4', models.ImageField(blank=True, upload_to='employees', verbose_name='Снимка долу дясно')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='Име (в т.ч. ресторант, механа и т.н.')),
                ('text1', models.TextField(blank=True, default='', verbose_name='Текст - първи абзац')),
                ('text2', models.TextField(blank=True, default='', verbose_name='Текст - втори абзац')),
                ('text3', models.TextField(blank=True, default='', verbose_name='Текст - трети абзац')),
            ],
            options={
                'verbose_name': 'Ресторант',
                'verbose_name_plural': 'Ресторанти',
            },
        ),
    ]
