# Generated by Django 4.2.11 on 2024-04-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
    ]
