# Generated by Django 4.2.11 on 2024-04-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review_alter_restaurant_photo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Раздел в менюто',
                'verbose_name_plural': 'Раздели в менюто',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant', verbose_name='Ресторант')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Раздел/група')),
            ],
            options={
                'verbose_name': 'Позиция в менюто',
                'verbose_name_plural': 'Позиции в менюто',
            },
        ),
    ]
