# Generated by Django 4.2.11 on 2024-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_group_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(blank=True, upload_to='menu', verbose_name='Снимка'),
        ),
    ]
