# Generated by Django 4.2.11 on 2024-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bookhour_service_remove_restaurant_text3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='ap_service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='ap_email',
            field=models.CharField(default='', max_length=50, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ap_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'обяд'), (2, 'вечеря')], default=2, help_text='тип на резервацията'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ap_phone',
            field=models.CharField(default='', max_length=14, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
