# Generated by Django 4.2.11 on 2024-04-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_appointment_ap_service_appointment_ap_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ap_message',
            field=models.TextField(blank=True, default='', verbose_name='Допълнителни изисквания'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ap_places',
            field=models.IntegerField(default=0, help_text='брой резержирани места', verbose_name='Брой хора'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ap_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'обяд'), (2, 'вечеря')], default=2, help_text='тип на резервацията', verbose_name='Тип'),
        ),
    ]
