# Generated by Django 4.2.11 on 2024-04-27 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_appointment_ap_message_appointment_ap_places_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ap_rest',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.restaurant', verbose_name='Ресторант'),
        ),
    ]
